module.exports = {
  mongodbError: 'MongoDB Error',
  singupDone: 'Congrats! You are successfully signed up',
  signupFailed: 'Opps...! signup failed',
  emailExist: 'Email already exist',
  nameNotFound: 'Name not found',
  emailNotFound: 'Email not found',
  passwordNotFound: 'Password not found',
  userLoggedIn: 'User logged in successfully',
  invalidCredential: 'Invalid user credential',
  invalidUser: 'Invalid user',
  postCreated: 'Post created successfully',
  postCreationFailed: 'Post creation failed',
  tokenHasExpired: 'Token has expired',
  tokenNotFound: 'Token not found',
  invalidToken: 'Invalid token',
  postFetched: 'All posts fetched successfully',
  postsNotFound: 'Posts not found',
  postFound: 'Post fetched successfully',
  postNotFound: 'Post not found',
  commentAdded: 'Congrats..! comment added successfully',
  invalidPostId: 'Invalid post id',
};
